apiVersion: v1
kind: Secret
metadata:
  name: proverbes-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
